### ISSUE TITLE
Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused 

### ISSUE THREAD

**Issue by anveshana99** [coderstape/freeCodeGram#1]
Hi i have followed you video but instead of sqlite i have taken mysql. when i'm trying to migrate i got "Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused" this error.
in .env file
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=

in config/database.php file
'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

**Comment by vicgonvt** [comment]
It might be an issue with your version of MySQL. You need to be using 5.7, if you are using 8 then it will error. Check your mysql version.
